### ISSUE TITLE
integration requirements not met

### ISSUE THREAD

**Issue by giodegas** [EMICVL/SDASU-07.11.2017-#1]
## Report testing against the [integration requirements](http://github.com/EMICVL/ProjectDocumentation/blob/master/Integration_requirements.md)

Point that need additional work for the scene/level to be integrated in the final global  prototype:

3. and 4. The package is compressed in rar format which is not necessary. The exported package is already zipped. Upload it as it comes out from Unity.

6. The folder structure is not compliant. See picture:

<img width="348" alt="schermata 2017-11-08 alle 07 56 32" src="https://user-images.githubusercontent.com/6838625/32535833-089afdf0-c45c-11e7-8ef3-2d23f69f7e77.png">
   
   after making the reqeusted fodler structure, put all assets that are necessary but do not fit into the AdditionalAssets folder.

13. No license file is found after importing the package. Please, put a License.txt file in the Scenes folder, as described in the requirements.

**Comment by giodegas** [comment]
if you submit you updaded package by today there is still a chance to be integrated in the final prototype.

**Comment by davitgoder** [comment]
Dear Giovanni,

I hope I met requirements, if there are any problems, please let me know
before integration is finished.

Best wishes

**Comment by giodegas** [comment]
This is the only submission which still does not met the requirements. Please fix it before the Tblisi meeting.

**Comment by giodegas** [comment]
The folder structure still does not met requirements:

Folders not admissible:

* PostProcessing 

Folders missing:

* Prefabs
* Sounds
* Sprites

please, submit a new _beta_ ASAP.

**Comment by giodegas** [comment]
<img width="345" alt="schermata 2017-11-28 alle 21 47 22" src="https://user-images.githubusercontent.com/6838625/33343778-d5b8b66c-d486-11e7-8b80-0ea65131b81c.png">

**Comment by giodegas** [comment]
now EMICVL_SDASU_Beta_1.3.unitypackage it looks ok. (y)
